package mods.timaxa007.module.weight;

import net.minecraft.init.Items;
import net.minecraft.item.Item;

public class WeightVanilaItems {

	public static float getVanilaItem(Item item, int metadata) {
		if (item == Items.iron_shovel) return IWeightVanilaItem.iron_shovel;
		else if (item == Items.iron_pickaxe) return IWeightVanilaItem.iron_pickaxe;
		else if (item == Items.iron_axe) return IWeightVanilaItem.iron_axe;
		else if (item == Items.flint_and_steel) return IWeightVanilaItem.flint_and_steel;
		else if (item == Items.apple) return IWeightVanilaItem.apple;
		else if (item == Items.bow) return IWeightVanilaItem.bow;
		else if (item == Items.arrow) return IWeightVanilaItem.arrow;
		else if (item == Items.coal && metadata == 0) return IWeightVanilaItem.coal;
		else if (item == Items.coal && metadata == 1) return IWeightVanilaItem.charcoal;
		else if (item == Items.diamond) return IWeightVanilaItem.diamond;
		else if (item == Items.iron_ingot) return IWeightVanilaItem.iron_ingot;
		else if (item == Items.gold_ingot) return IWeightVanilaItem.gold_ingot;
		else if (item == Items.iron_sword) return IWeightVanilaItem.iron_sword;
		else if (item == Items.wooden_sword) return IWeightVanilaItem.wooden_sword;
		else if (item == Items.wooden_shovel) return IWeightVanilaItem.wooden_shovel;
		else if (item == Items.wooden_pickaxe) return IWeightVanilaItem.wooden_pickaxe;
		else if (item == Items.wooden_axe) return IWeightVanilaItem.wooden_axe;
		else if (item == Items.stone_sword) return IWeightVanilaItem.stone_sword;
		else if (item == Items.stone_shovel) return IWeightVanilaItem.stone_shovel;
		else if (item == Items.stone_pickaxe) return IWeightVanilaItem.stone_pickaxe;
		else if (item == Items.stone_axe) return IWeightVanilaItem.stone_axe;
		else if (item == Items.diamond_sword) return IWeightVanilaItem.diamond_sword;
		else if (item == Items.diamond_shovel) return IWeightVanilaItem.diamond_shovel;
		else if (item == Items.diamond_pickaxe) return IWeightVanilaItem.diamond_pickaxe;
		else if (item == Items.diamond_axe) return IWeightVanilaItem.diamond_axe;
		else if (item == Items.stick) return IWeightVanilaItem.stick;
		else if (item == Items.bowl) return IWeightVanilaItem.bowl;
		else if (item == Items.mushroom_stew) return IWeightVanilaItem.mushroom_stew;
		else if (item == Items.golden_sword) return IWeightVanilaItem.golden_sword;
		else if (item == Items.golden_shovel) return IWeightVanilaItem.golden_shovel;
		else if (item == Items.golden_pickaxe) return IWeightVanilaItem.golden_pickaxe;
		else if (item == Items.golden_axe) return IWeightVanilaItem.golden_axe;
		else if (item == Items.string) return IWeightVanilaItem.string;
		else if (item == Items.feather) return IWeightVanilaItem.feather;
		else if (item == Items.gunpowder) return IWeightVanilaItem.gunpowder;
		else if (item == Items.wooden_hoe) return IWeightVanilaItem.wooden_hoe;
		else if (item == Items.stone_hoe) return IWeightVanilaItem.stone_hoe;
		else if (item == Items.iron_hoe) return IWeightVanilaItem.iron_hoe;
		else if (item == Items.diamond_hoe) return IWeightVanilaItem.diamond_hoe;
		else if (item == Items.golden_hoe) return IWeightVanilaItem.golden_hoe;
		else if (item == Items.wheat_seeds) return IWeightVanilaItem.wheat_seeds;
		else if (item == Items.wheat) return IWeightVanilaItem.wheat;
		else if (item == Items.bread) return IWeightVanilaItem.bread;
		else if (item == Items.leather_helmet) return IWeightVanilaItem.leather_helmet;
		else if (item == Items.leather_chestplate) return IWeightVanilaItem.leather_chestplate;
		else if (item == Items.leather_leggings) return IWeightVanilaItem.leather_leggings;
		else if (item == Items.leather_boots) return IWeightVanilaItem.leather_boots;
		else if (item == Items.chainmail_helmet) return IWeightVanilaItem.chainmail_helmet;
		else if (item == Items.chainmail_chestplate) return IWeightVanilaItem.chainmail_chestplate;
		else if (item == Items.chainmail_leggings) return IWeightVanilaItem.chainmail_leggings;
		else if (item == Items.chainmail_boots) return IWeightVanilaItem.chainmail_boots;
		else if (item == Items.iron_helmet) return IWeightVanilaItem.iron_helmet;
		else if (item == Items.iron_chestplate) return IWeightVanilaItem.iron_chestplate;
		else if (item == Items.iron_leggings) return IWeightVanilaItem.iron_leggings;
		else if (item == Items.iron_boots) return IWeightVanilaItem.iron_boots;
		else if (item == Items.diamond_helmet) return IWeightVanilaItem.diamond_helmet;
		else if (item == Items.diamond_chestplate) return IWeightVanilaItem.diamond_chestplate;
		else if (item == Items.diamond_leggings) return IWeightVanilaItem.diamond_leggings;
		else if (item == Items.diamond_boots) return IWeightVanilaItem.diamond_boots;
		else if (item == Items.golden_helmet) return IWeightVanilaItem.golden_helmet;
		else if (item == Items.golden_chestplate) return IWeightVanilaItem.golden_chestplate;
		else if (item == Items.golden_leggings) return IWeightVanilaItem.golden_leggings;
		else if (item == Items.golden_boots) return IWeightVanilaItem.golden_boots;
		else if (item == Items.flint) return IWeightVanilaItem.flint;
		else if (item == Items.porkchop) return IWeightVanilaItem.porkchop;
		else if (item == Items.cooked_porkchop) return IWeightVanilaItem.cooked_porkchop;
		else if (item == Items.painting) return IWeightVanilaItem.painting;
		else if (item == Items.golden_apple && metadata == 0) return IWeightVanilaItem.golden_apple_0;
		else if (item == Items.golden_apple && metadata == 1) return IWeightVanilaItem.golden_apple_1;
		else if (item == Items.sign) return IWeightVanilaItem.sign;
		else if (item == Items.wooden_door) return IWeightVanilaItem.wooden_door;
		else if (item == Items.bucket) return IWeightVanilaItem.bucket;
		else if (item == Items.water_bucket) return IWeightVanilaItem.water_bucket;
		else if (item == Items.lava_bucket) return IWeightVanilaItem.lava_bucket;
		else if (item == Items.minecart) return IWeightVanilaItem.minecart;
		else if (item == Items.saddle) return IWeightVanilaItem.saddle;
		else if (item == Items.iron_door) return IWeightVanilaItem.iron_door;
		else if (item == Items.redstone) return IWeightVanilaItem.redstone;
		else if (item == Items.snowball) return IWeightVanilaItem.snowball;
		else if (item == Items.boat) return IWeightVanilaItem.boat;
		else if (item == Items.leather) return IWeightVanilaItem.leather;
		else if (item == Items.milk_bucket) return IWeightVanilaItem.milk_bucket;
		else if (item == Items.brick) return IWeightVanilaItem.brick;
		else if (item == Items.clay_ball) return IWeightVanilaItem.clay_ball;
		else if (item == Items.reeds) return IWeightVanilaItem.reeds;
		else if (item == Items.paper) return IWeightVanilaItem.paper;
		else if (item == Items.book) return IWeightVanilaItem.book;
		else if (item == Items.slime_ball) return IWeightVanilaItem.slime_ball;
		else if (item == Items.chest_minecart) return IWeightVanilaItem.chest_minecart;
		else if (item == Items.furnace_minecart) return IWeightVanilaItem.furnace_minecart;
		else if (item == Items.egg) return IWeightVanilaItem.egg;
		else if (item == Items.compass) return IWeightVanilaItem.compass;
		else if (item == Items.fishing_rod) return IWeightVanilaItem.fishing_rod;
		else if (item == Items.clock) return IWeightVanilaItem.clock;
		else if (item == Items.glowstone_dust) return IWeightVanilaItem.glowstone_dust;
		else if (item == Items.fish && metadata == 0) return IWeightVanilaItem.fish_0;
		else if (item == Items.fish && metadata == 1) return IWeightVanilaItem.fish_1;
		else if (item == Items.fish && metadata == 2) return IWeightVanilaItem.fish_2;
		else if (item == Items.fish && metadata == 3) return IWeightVanilaItem.fish_3;
		else if (item == Items.cooked_fished && metadata == 0) return IWeightVanilaItem.cooked_fished_0;
		else if (item == Items.cooked_fished && metadata == 1) return IWeightVanilaItem.cooked_fished_1;
		else if (item == Items.cooked_fished && metadata == 2) return IWeightVanilaItem.cooked_fished_2;
		else if (item == Items.cooked_fished && metadata == 3) return IWeightVanilaItem.cooked_fished_3;
		else if (item == Items.dye && metadata == 0) return IWeightVanilaItem.dye_0;
		else if (item == Items.dye && metadata == 1) return IWeightVanilaItem.dye_1;
		else if (item == Items.dye && metadata == 2) return IWeightVanilaItem.dye_2;
		else if (item == Items.dye && metadata == 3) return IWeightVanilaItem.dye_3;
		else if (item == Items.dye && metadata == 4) return IWeightVanilaItem.dye_4;
		else if (item == Items.dye && metadata == 5) return IWeightVanilaItem.dye_5;
		else if (item == Items.dye && metadata == 6) return IWeightVanilaItem.dye_6;
		else if (item == Items.dye && metadata == 7) return IWeightVanilaItem.dye_7;
		else if (item == Items.dye && metadata == 8) return IWeightVanilaItem.dye_8;
		else if (item == Items.dye && metadata == 9) return IWeightVanilaItem.dye_9;
		else if (item == Items.dye && metadata == 10) return IWeightVanilaItem.dye_10;
		else if (item == Items.dye && metadata == 11) return IWeightVanilaItem.dye_11;
		else if (item == Items.dye && metadata == 12) return IWeightVanilaItem.dye_12;
		else if (item == Items.dye && metadata == 13) return IWeightVanilaItem.dye_13;
		else if (item == Items.dye && metadata == 14) return IWeightVanilaItem.dye_14;
		else if (item == Items.dye && metadata == 15) return IWeightVanilaItem.dye_15;
		else if (item == Items.bone) return IWeightVanilaItem.bone;
		else if (item == Items.sugar) return IWeightVanilaItem.sugar;
		else if (item == Items.cake) return IWeightVanilaItem.cake;
		else if (item == Items.bed) return IWeightVanilaItem.bed;
		else if (item == Items.repeater) return IWeightVanilaItem.repeater;
		else if (item == Items.cookie) return IWeightVanilaItem.cookie;
		else if (item == Items.filled_map) return IWeightVanilaItem.filled_map;
		else if (item == Items.shears) return IWeightVanilaItem.shears;
		else if (item == Items.melon) return IWeightVanilaItem.melon;
		else if (item == Items.pumpkin_seeds) return IWeightVanilaItem.pumpkin_seeds;
		else if (item == Items.melon_seeds) return IWeightVanilaItem.melon_seeds;
		else if (item == Items.beef) return IWeightVanilaItem.beef;
		else if (item == Items.cooked_beef) return IWeightVanilaItem.cooked_beef;
		else if (item == Items.chicken) return IWeightVanilaItem.chicken;
		else if (item == Items.cooked_chicken) return IWeightVanilaItem.cooked_chicken;
		else if (item == Items.rotten_flesh) return IWeightVanilaItem.rotten_flesh;
		else if (item == Items.ender_pearl) return IWeightVanilaItem.ender_pearl;
		else if (item == Items.blaze_rod) return IWeightVanilaItem.blaze_rod;
		else if (item == Items.ghast_tear) return IWeightVanilaItem.ghast_tear;
		else if (item == Items.gold_nugget) return IWeightVanilaItem.gold_nugget;
		else if (item == Items.nether_wart) return IWeightVanilaItem.nether_wart;
		else if (item == Items.potionitem) return IWeightVanilaItem.potionitem;
		else if (item == Items.glass_bottle) return IWeightVanilaItem.glass_bottle;
		else if (item == Items.spider_eye) return IWeightVanilaItem.spider_eye;
		else if (item == Items.fermented_spider_eye) return IWeightVanilaItem.fermented_spider_eye;
		else if (item == Items.blaze_powder) return IWeightVanilaItem.blaze_powder;
		else if (item == Items.magma_cream) return IWeightVanilaItem.magma_cream;
		else if (item == Items.brewing_stand) return IWeightVanilaItem.brewing_stand;
		else if (item == Items.cauldron) return IWeightVanilaItem.cauldron;
		else if (item == Items.ender_eye) return IWeightVanilaItem.ender_eye;
		else if (item == Items.speckled_melon) return IWeightVanilaItem.speckled_melon;
		else if (item == Items.spawn_egg) return IWeightVanilaItem.spawn_egg;
		else if (item == Items.experience_bottle) return IWeightVanilaItem.experience_bottle;
		else if (item == Items.fire_charge) return IWeightVanilaItem.fire_charge;
		else if (item == Items.writable_book) return IWeightVanilaItem.writable_book;
		else if (item == Items.written_book) return IWeightVanilaItem.written_book;
		else if (item == Items.emerald) return IWeightVanilaItem.emerald;
		else if (item == Items.item_frame) return IWeightVanilaItem.item_frame;
		else if (item == Items.flower_pot) return IWeightVanilaItem.flower_pot;
		else if (item == Items.carrot) return IWeightVanilaItem.carrot;
		else if (item == Items.potato) return IWeightVanilaItem.potato;
		else if (item == Items.baked_potato) return IWeightVanilaItem.baked_potato;
		else if (item == Items.poisonous_potato) return IWeightVanilaItem.poisonous_potato;
		else if (item == Items.map) return IWeightVanilaItem.map;
		else if (item == Items.golden_carrot) return IWeightVanilaItem.golden_carrot;
		else if (item == Items.skull && metadata == 0) return IWeightVanilaItem.skull_skelet;
		else if (item == Items.skull && metadata == 1) return IWeightVanilaItem.skull_skelet_witcher;
		else if (item == Items.skull && metadata == 2) return IWeightVanilaItem.skull_zombie;
		else if (item == Items.skull && metadata == 3) return IWeightVanilaItem.skull_player;
		else if (item == Items.skull && metadata == 4) return IWeightVanilaItem.skull_creeper;
		else if (item == Items.carrot_on_a_stick) return IWeightVanilaItem.carrot_on_a_stick;
		else if (item == Items.nether_star) return IWeightVanilaItem.nether_star;
		else if (item == Items.pumpkin_pie) return IWeightVanilaItem.pumpkin_pie;
		else if (item == Items.fireworks) return IWeightVanilaItem.fireworks;
		else if (item == Items.firework_charge) return IWeightVanilaItem.firework_charge;
		else if (item == Items.enchanted_book) return IWeightVanilaItem.enchanted_book;
		else if (item == Items.comparator) return IWeightVanilaItem.comparator;
		else if (item == Items.netherbrick) return IWeightVanilaItem.netherbrick;
		else if (item == Items.quartz) return IWeightVanilaItem.quartz;
		else if (item == Items.tnt_minecart) return IWeightVanilaItem.tnt_minecart;
		else if (item == Items.hopper_minecart) return IWeightVanilaItem.hopper_minecart;
		else if (item == Items.iron_horse_armor) return IWeightVanilaItem.iron_horse_armor;
		else if (item == Items.golden_horse_armor) return IWeightVanilaItem.golden_horse_armor;
		else if (item == Items.diamond_horse_armor) return IWeightVanilaItem.diamond_horse_armor;
		else if (item == Items.lead) return IWeightVanilaItem.lead;
		else if (item == Items.name_tag) return IWeightVanilaItem.name_tag;
		else if (item == Items.command_block_minecart) return IWeightVanilaItem.command_block_minecart;
		else if (item == Items.record_13) return IWeightVanilaItem.record_13;
		else if (item == Items.record_cat) return IWeightVanilaItem.record_cat;
		else if (item == Items.record_blocks) return IWeightVanilaItem.record_blocks;
		else if (item == Items.record_chirp) return IWeightVanilaItem.record_chirp;
		else if (item == Items.record_far) return IWeightVanilaItem.record_far;
		else if (item == Items.record_mall) return IWeightVanilaItem.record_mall;
		else if (item == Items.record_mellohi) return IWeightVanilaItem.record_mellohi;
		else if (item == Items.record_stal) return IWeightVanilaItem.record_stal;
		else if (item == Items.record_strad) return IWeightVanilaItem.record_strad;
		else if (item == Items.record_ward) return IWeightVanilaItem.record_ward;
		else if (item == Items.record_11) return IWeightVanilaItem.record_11;
		else if (item == Items.record_wait) return IWeightVanilaItem.record_wait;
		else return 0.0F;
	}

}
